In [35]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np


n = int(input())
X = []
for i in range(n):
    X.append([float(x) for x in input().split()])
y = [int(x) for x in input().split()]
datapoint = [float(x) for x in input().split()]

df = pd.DataFrame(X)
print(df)

6
1 3
3 5
5 7
3 1
5 3
7 5
1 1 1 0 0 0
2 4
     0    1
0  1.0  3.0
1  3.0  5.0
2  5.0  7.0
3  3.0  1.0
4  5.0  3.0
5  7.0  5.0


In [36]:
X_arr = df.values
print(X_arr, type(X_arr), X_arr.shape)

[[1. 3.]
 [3. 5.]
 [5. 7.]
 [3. 1.]
 [5. 3.]
 [7. 5.]] <class 'numpy.ndarray'> (6, 2)


In [37]:
y_arr = np.array(y)
print(y_arr, type(y_arr), y_arr.shape)

[1 1 1 0 0 0] <class 'numpy.ndarray'> (6,)


In [38]:
arr_datapoint = np.array(datapoint)
print(arr_datapoint, arr_datapoint.shape)

[2. 4.] (2,)


In [47]:
model = LogisticRegression()
model.fit(X_arr, y_arr)
print(model.predict(X))

[1 1 1 0 0 0]


In [48]:
result = model.predict([arr_datapoint])
print(type(result), int(result[0]))

<class 'numpy.ndarray'> 1


In [41]:
print(model.score(X_arr, y_arr))

1.0
